name: Minimal

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions / test / test 22"
        - name: Output Date
        run: echo $(date)

